language: r
sudo: false
cache: packages
r_packages:
  - rmarkdown
  - xaringan
  - ggplot2
  - knitr
  - ggthemes
  - plotly
  - gganimate
  - scatterplot3d
  - plot3D
  - rayshader
  - rgl
  - gridExtra
  - cowplot
r_github_packages:
  - thomasp85/patchwork
os:
  - osx
script:
  - R -e "rmarkdown::render('ggplot.Rmd')"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public